services:
  web-app:
    build: ./web-app
    container_name: web-app
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    volumes:
      - ./web-app:/app
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge