name: Web App CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-app

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t web-app .
      
      - name: Run unit tests in Docker container
        env:
          MONGO_URI: ${{secrets.ATLAS_MONGO_URI}}
        run: docker run --rm -e MONGO_URI=${{secrets.ATLAS_MONGO_URI}} web-app pytest

  push-image:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/swe-project5-team-cc-web-app:latest web-app

      - name: Push Docker image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/swe-project5-team-cc-web-app:latest
